# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Josh Schertz
description: >
  Techie, visionary, optimist.
url: "https://joshschertz.com"
logo: /assets/img/logo-black.PNG

# Google services
google_analytics: UA-66373915-1

# Social media usernames
github:
    username: camisatx
twitter:
    username: joshuaschertz
linkedin:
    username: joshuaschertz

# Social media profiles used by Google's Knowledge Graph
social:
    name: Josh Schertz
    links:
      - https://twitter.com/joshuaschertz
      - https://linkedin.com/in/joshuaschertz
      - https://github.com/camisatx

# Build settings
markdown: kramdown
exclude:
    - Gemfile
    - Gemfile.lock
    - .gitignore
    - README.md
sass:
    sass_dir: _sass
kramdown:
  input: GFM
permalink: pretty

gems:
  - jekyll-feed     # Enable automatic Atom feed creation
  - jekyll-sitemap  # Github Pages will automatically generate a sitemap
  - jekyll-seo-tag  # Enable automatic generation of metadata for seo
  - jekyll-redirect-from    # Redirect prior URL to the current URL

# Treat each image in `assets/img` as if it had front matter of `image: true`.
# This allows you to use a for loop to iterate through images.
# https://jekyllrb.com/docs/static-files/
defaults:
  - scope:
        path: "assets/img"
    values:
        image: true
